repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-symlinks
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-yaml
        args:
          - --unsafe

exclude: ^.github/
