output:
  file: README.md
  mode: inject

settings:
  hide-empty: false #true
  # recursive: true

recursive:
  enabled: true
  # path: terraform
  include-main: true


sort:
  enabled: true
  by: required

sections:
  show:
    - providers
    - inputs
    - outputs
    - resources
    - modules
