output:
  file: ../README.md
  mode: inject

settings:
  hide-empty: false #true
  # recursive: true
  # working-dir: .,terraform/azure,terraform/azure/az_modules/gcp_dns_zone,terraform/aws_gcp

# recursive:
#   enabled: true
#   path: terraform
#   include-main: true


sort:
  enabled: true
  by: required

sections:
  show:
    - providers
    - inputs
    - outputs
    - resources
    - modules
    
content: |-
  {{ .Requirements }}
  ## Usage
  Basic usage of this module is as follows:
  ```hcl
  module "example" {
    {{"\t"}} source  = "<module-path>"
  {{- if .Module.RequiredInputs }}
    {{"\n\t"}} # Required variables
    {{- range .Module.RequiredInputs }}
    {{"\t"}} {{ .Name }}  = {{ .GetValue }}
    {{- end }}
    {{- end }}
  {{- if .Module.OptionalInputs }}
    {{"\n\t"}} # Optional variables
    {{- range .Module.OptionalInputs }}
    {{"\t"}} {{ .Name }}  = {{ .GetValue | printf "%s" }}
    {{- end }}
    {{- end }}
  }
  ```
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
